### PR TITLE
Initial MVP of projects' map with react,leaflet and chakra

### PR DESCRIPTION
**Pull request by emiltsokov**

### CODE REVIEW

**Comment by lyudmil** [comment]
Looks great, thanks for putting this together, @emiltsokov!

A couple of questions we can already get feedback on from a potential product owner:

1. Will the final version of the map be displayed full screen as it is here or does it need live alongside other website chrome?
2. How do we feel about the pins and the overlay they display when clicked? Is that a feasible approach for the MVP of the map? Do we have to worry about being able to mark whole areas or roads?
3. How many pins do we think is reasonable to display at the initial zoom level? How many do we have to display?
4. If we have too many pins to display, do we hide some depending on zoom level? Group them?

Using this has unfortunately confirmed my reservations about using a map to drive the UI for this. It's been super useful, though, because I can now articulate my worries better. Here are my notes:

* A lot of the features of Sofia need to be preserved in order for me to get my bearings – I can't find my neighborhood unless I know where the Ring Road and Tsarigradsko Shose are. However, most features of the city are just visual noise, which prevents me from seeing the pins and getting the overall message.

* I worry about the number of and type of objects we have to visualize on the map. It'll get busy, and I worry that it's going to get cluttered.

* The point of the map is so that if I live in Lyulin 10 I can find what Spasi Sofia has done for me locally. To do that I need to:
  - find Lyulin 10 on the map, which I don't think everyone will be able to
  - if there are too many pins, zoom in to see them
  - hunt-and-click each one to find out more, which I can do in a random order, so I might miss the biggest thing

* I think the above procedure is very difficult to get right in terms of UX. A lot of the work – navigating, zooming, hunting for pins – is unrelated to the user task. It also doesn't make the presentation of the information easier or more attractive. My question, therefore, is: apart from being impressive in terms of engineering, how is a map objectively better than a list of accomplishments categorized by region?

**Comment by emiltsokov** [comment]
Thank you @lyudmil
The questions you raise around the project are quite useful and constructive.

**First some answers/thoughts on your reservations regarding UI/UX**

_A lot of the features of Sofia need to be preserved in order for me to get my bearings – I can't find my neighborhood unless I know where the Ring Road and Tsarigradsko Shose are. However, most features of the city are just visual noise, which prevents me from seeing the pins and getting the overall message. -_ 
 I think this is fixable by 
- custom images for pins (even different for different project types/topic)  
https://github.com/SpasiSofia/projects-map/pull/1/files#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67R27

- also the Tile Layer for the map can be quite different with much less noise
https://github.com/SpasiSofia/projects-map/pull/1/files#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67R27

eg. check [Monochrome](http://tile.openstreetmap.fr/) here http://tile.openstreetmap.fr/
this could be also UX choice for the user to switch tile layers, 
also we can have nice polygon shapes with Sofia quarters!  

_I worry about the number of and type of objects we have to visualise on the map. It'll get busy, and I worry that it's going to get cluttered._
This is fixable by grouping markers for specific zoom levels
https://github.com/Leaflet/Leaflet.markercluster

_The point of the map is so that if I live in Lyulin 10 I can find what Spasi Sofia has done for me locally. To do that I need to:_
- as already proposed we can have nice polygon shapes with Sofia quarters!  
- we can have filtering by quarter will explain further my idea around filtering!

**I'll try to answer some of the product owner questions as I can see them at the moment**

_Will the final version of the map be displayed full screen as it is here or does it need live alongside other website chrome?_
This app can be embedded in an Iframe and live inside the website also.

_How do we feel about the pins and the overlay they display when clicked? Is that a feasible approach for the MVP of the map?_
I was thinking to implement previous next navigation buttons inside the overlay.

 _Do we have to worry about being able to mark whole areas or roads?_
This is tricky and crucial question for the projects without specific place for example proposal about boulevards or for example information system about city transport. However several approaches could be considered. Considerations are  do we need  project markers different than pins, and if yes how clear we can represent those?


_How many pins do we think is reasonable to display at the initial zoom level? How many do we have to display?_
This seems like implementation question. as we have a tool for this - grouping-clustering

If we have too many pins to display, do we hide some depending on zoom level? Group them?
Same like the previous one.

**And finally some additional questions I have towards the "product owners"()**
1. What is the data/content about every project we want to present on the map ?
2. Should we apply filtering for projects if yes by which criteria?
- Type of project (currently every project could have several topics) see https://www.notion.so/beweb/db7eed10b91643d78be8adbf52a91e2d
- Quarter
- Date 
3. We plan to connect this with timeline items in the new website which will automatically feed this project map widget as manual update will require duplicate work

cc @Thusnake

**Review by Thusnake — APPROVED** [review]
This is a great demo. The code looks good to me and we need to continue discussions and development on it steadily to get some idea of what we want it to look like in the end.

**Comment by Thusnake** [comment]
On your questions:

- Will the final version of the map be displayed full screen as it is here or does it need live alongside other website chrome?

If it's going to be interactive, it must be versatile enough to be able to be displayed in any resolution. As Emil answered, this version can already do that.

- How do we feel about the pins and the overlay they display when clicked? Is that a feasible approach for the MVP of the map? Do we have to worry about being able to mark whole areas or roads?

In my opinion pins are boring and unattractive. If we can draw other shapes I think we can come up with something much nicer. The overlay is nice, though subject to discussion still. The ability to mark areas and especially roads is up for discussion as well and it's very important to clear that question up early.

- How many pins do we think is reasonable to display at the initial zoom level? How many do we have to display?

We need to find this out empirically. Unfortunately, that would require geotagging all items from the timelines now and the timelines aren't even close to finished (in terms of content). We could try estimating instead by looking up all events/achivements in a certain area and building up a local accurate mock.

- If we have too many pins to display, do we hide some depending on zoom level? Group them?

This depends on how the map will be interacted with. If it's going to be zoomable then we must consider it. If it's going to stay at a static zoom level then grouping won't make sense.

- What is the data/content about every project we want to present on the map?

As much as possible as long as it looks neat and well-prioritized. This is the Design team's job.

- Should we apply filtering for projects if yes by which criteria?

I'd personally prefer as many as possible, but I'm not sure if it's a good idea. This needs to be discussed.

- We plan to connect this with timeline items in the new website which will automatically feed this project map widget as manual update will require duplicate work

Yes.

**Comment by emiltsokov** [comment]
Just a quick follow up on the content  that's going to feed the map with projects that was discussed with Boris and Tanya on the first demo.
The idea is that there are going to be 2 different feeds for it.
First will be the projects that the website projects (with timelines).
Second will be a datasource (preferably GSheet) that will be populated with "smaller" projects, actions, activities etc. that did not make it to the website projects/timelines but also have value and could be showed on the map. (note: so we are not showing only achievements but also any kind of actions/projects)
Preferably this second field will be populated by a Google form that validates the required input.
I have already made issue for that here 
https://github.com/SpasiSofia/projects-map/issues/3

Също предлагам да минем на български за дискусиите в този проект. 🇧🇬

**Pull request merged**
